name: 'Register Build'
description: |
  Register a deploy for use with dot.Deploy. See the documentation for more information.
  This action to be placed at any point in your workflow. It uses pre-processing and post-processing to make sure that
  the deployment is registered correctly.
outputs:
  version:
    description: "Outputs the build version that should be deployed"
  environment:
    description: "Outputs the environment that the build should be deployed to"
  deployment_type:
    description: "Outputs the type of deployment that should be performed"
  deployment_id:
    description: "Outputs the dot.Deploy deployment ID"
runs:
  using: node20
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  pre: "dist/pre/index.js"
