name: 'Register Build'
description: |
  Register a deploy for use with dot.Deploy. See the documentation for more information.
  This action to be placed at any point in your workflow. It uses pre-processing and post-processing to make sure that
  the deployment is registered correctly.
outputs:
  version:
    description: "Outputs the build version that should be deployed"
runs:
  using: node20
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  pre: "dist/pre/index.js"
